server:
  port: 8040
spring:
  data:
    mongodb:
      username: devraj
      password: devraj
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:org.asymptotes.notification.entities.order.OrderConfirmation,paymentConfirmation:org.asymptotes.notification.entities.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: devraj
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000